program CALCULO;
var
  A, B, R : integer;
begin
  write('Entre um valor para A: '); readln(A);
  write('Entre um valor para B: '); readln(B);
  writeln;
  R := A + B;
  writeln('O resultado corresponde a: ', R);
  writeln;
  write('Entre um valor para A: '); readln(A);
  write('Entre um valor para B: '); readln(B);
  writeln;
  R := A + B;
  writeln('O resultado corresponde a: ', R);
  writeln;
  write('Entre um valor para A: '); readln(A);
  write('Entre um valor para B: '); readln(B);
  writeln;
  R := A + B;
  writeln('O resultado corresponde a: ', R);
  writeln;
  write('Entre um valor para A: '); readln(A);
  write('Entre um valor para B: '); readln(B);
  writeln;
  R := A + B;
  writeln('O resultado corresponde a: ', R);
  writeln;
  write('Entre um valor para A: '); readln(A);
  write('Entre um valor para B: '); readln(B);
  writeln;
  R := A + B;
  writeln('O resultado corresponde a: ', R);
  writeln;
end.

